// Generated by tools/make-dev-code.js. Holds only a salted hash of the access code, never the code itself.
export const DEV_CONFIG = { salt: '53598a094b1c456ad556aab8edbb2723', hash: '9cde6d15c2814ecebc92ed7c3e7e7722ae1c5a573d2c5c216953593482deeb79' };
